# Generated by Django 4.0.5 on 2022-06-27 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
