# Generated by Django 4.0.5 on 2022-06-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_email_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='email',
            name='created',
        ),
    ]
