# Generated by Django 4.0.5 on 2022-06-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_email_options_remove_email_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
