version: '3.9'

volumes:
  rabbitmq-data:
  rabbitmq-log:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      # - ./backend/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      # - ./backend/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net
    environment:
      - RABBITMQ_DEFAULT_USER=rabb
      - RABBITMQ_DEFAULT_PASS=rabb

  be:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: python manage.py runserver be:8000
    volumes:
      - ./backend:/code
    ports:
      - '8000:8000'
    networks:
      - rabbitmq_go_net
    depends_on:
      - rabbitmq
      - celery

  web:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    volumes:
      - ./front-end/dist:/usr/share/nginx/html
    ports:
      - '3000:80'

  celery:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: celery -A backendDevopsChallenge worker -l info
    volumes:
      - ./backend:/code
    environment:
      - RABBITMQ_BROKER_URL=amqp://rabb:rabb@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
